version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    # Backend same docker network se connect karega; port expose ki zaroorat nahi.
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # (Optional) Healthcheck — agar mongosh available ho to uncomment karein
    # healthcheck:
    #   test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      # NOTE: auth credentials + authSource=admin IMPORTANT
      - MONGO_URI=mongodb://root:example@mongo:27017/gb-pizza?authSource=admin
      - JWT_SECRET=change_me
      - STRIPE_SECRET_KEY=sk_test_change_me
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      # Agar upar healthcheck enable karein to:
      # mongo:
      #   condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    container_name: admin
    restart: unless-stopped
    ports:
      - "4001:80"
    depends_on:
      - backend

volumes:
  mongo-data:
